"""Shared limits for conversation, tools, and debug views."""


SESSION_HISTORY_LIMIT = 50

HISTORY_TOKEN_BUDGET = 80_000
HISTORY_KEEP_RECENT = 20
STREAM_RETRY_ATTEMPTS = 3

READ_FILE_DEFAULT_LIMIT = 2000
SEARCH_IN_FILE_DEFAULT_LIMIT = 50
SEARCH_IN_FILE_MAX_LIMIT = 200
SEARCH_FILES_MAX_RESULTS = 50

RUN_COMMAND_TIMEOUT_S = 300
RUN_COMMAND_MAX_OUTPUT_CHARS = 5000
TOOL_RESULT_PREVIEW_CHARS = 500
# 后台命令注册表里"已退出"的进程最多保留几个（仍可被 read_background_output 读最终输出）。
# 超过则淘汰最老的已退出项，防长会话里崩溃/跑完的后台任务连同 2000 行输出 deque 无限驻留。
# 运行中的进程从不被淘汰。
BG_MAX_RETAINED_EXITED = 10

DEBUG_MAX_RECORDS = 50
DEBUG_BASE64_PREVIEW_CHARS = 200
DEBUG_TEXT_PREVIEW_CHARS = 4000
DEBUG_SYSTEM_PROMPT_PREVIEW_CHARS = 1500
DEBUG_MESSAGE_PREVIEW_CHARS = 600
DEBUG_RESPONSE_PREVIEW_CHARS = 2000

# 会话历史压缩（Compaction）
COMPACTION_SUMMARY_MAX_CHARS = 1500  # 压缩摘要长度上限（字符）

# 长期记忆相关
MEMORY_MAX_CHARS = 4000  # 注入 system prompt 的记忆文本上限
MEMORY_FACT_MAX_LENGTH = 200  # 单条事实最大长度
